# pip install

In [ ]:
!pip install datawig

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: datawig in /usr/local/lib/python3.8/dist-packages (0.2.0)
Requirement already satisfied: mxnet==1.4.0 in /usr/local/lib/python3.8/dist-packages (from datawig) (1.4.0)
Requirement already satisfied: scikit-learn[alldeps]==0.22.1 in /usr/local/lib/python3.8/dist-packages (from datawig) (0.22.1)
Requirement already satisfied: pandas==0.25.3 in /usr/local/lib/python3.8/dist-packages (from datawig) (0.25.3)
Requirement already satisfied: typing==3.6.6 in /usr/local/lib/python3.8/dist-packages (from datawig) (3.6.6)
Collecting numpy<1.15.0,>=1.8.2
  Using cached numpy-1.14.6-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.8/dist-packages (from mxnet==1.4.0->datawig) (2.23.0)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.8/dist-packages (from mxnet==1.4.0->datawig) (0.8.4)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.8/dist-packages (from pandas==0.25.3->datawig) (2022.6)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.8/dist-packages (from pandas==0.25.3->datawig) (2.8.2)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn[alldeps]==0.22.1->datawig) (1.5.4)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn[alldeps]==0.22.1->datawig) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.6.1->pandas==0.25.3->datawig) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (2.10)
ERROR: Operation cancelled by user

In [ ]:
!pip install impyute

In [ ]:
!pip install numpy==1.16.6

# Import

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 결측치 처리

In [ ]:
# 결측치 처리 관련
import datawig
from impyute.imputation.cs import mice

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/dataset/2022_겨울_경진대회_dataset/total_credit.csv',index_col=0)

In [ ]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,DAYS_BIRTH,DAYS_REGISTRATION,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,EXT_SOURCE_1,EXT_SOURCE_2,...,new_EDU_LEVEL,new_EMPLOYED_DAYS,new_ECONOMIC_POPULATION,previous_AMT_ANNUITY,previous_AMT_CREDIT,previous_AMT_GOODS_PRICE,previous_ID_COUNT,previous_APPLICATION_TO_CREDIT,previous_REFUSED_COUNT,previous_DAY_DECISION
0,100002,1,Cash loans,M,-9461,-3648.0,2,10,0.083037,0.262949,...,1,-637.0,1.0,9251.775000,179055.00,179055.000,1.0,0.000,0.0,606.000000
1,100003,0,Cash loans,F,-16765,-1186.0,1,11,0.311267,0.622246,...,0,-1188.0,2.0,56553.990000,484191.00,435436.500,3.0,48754.500,0.0,1305.000000
2,100004,0,Revolving loans,M,-19046,-4260.0,2,9,NaN,0.555912,...,1,-225.0,1.0,5357.250000,20106.00,24282.000,1.0,-4176.000,0.0,815.000000
3,100006,0,Cash loans,F,-19005,-9833.0,2,17,NaN,0.650442,...,1,-3039.0,2.0,23651.175000,291695.50,408304.890,9.0,19492.240,1.0,272.444444
4,100007,0,Cash loans,M,-19932,-4311.0,2,11,NaN,0.322738,...,1,-3038.0,1.0,12278.805000,166638.75,150530.250,6.0,16108.500,0.0,1222.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307504,456251,0,Cash loans,M,-9327,-8456.0,1,15,0.145570,0.681632,...,1,-236.0,1.0,6605.910000,40455.00,40455.000,1.0,0.000,0.0,273.000000
307505,456252,0,Cash loans,F,-20775,-4388.0,2,8,NaN,0.115992,...,1,NaN,1.0,10074.465000,56821.50,57595.500,1.0,-774.000,0.0,2497.000000
307506,456253,0,Cash loans,F,-14966,-6737.0,3,9,0.744026,0.535722,...,0,-7921.0,1.0,4770.405000,20625.75,24162.750,2.0,-3537.000,0.0,2380.000000
307507,456254,1,Cash loans,F,-11961,-2562.0,2,9,NaN,0.514163,...,1,-4786.0,2.0,10681.132500,134439.75,121317.750,2.0,13122.000,0.0,299.500000
307508,456255,0,Cash loans,F,-16856,-5128.0,1,20,0.734460,0.708569,...,0,-1262.0,2.0,20775.391875,424431.00,362770.875,8.0,61660.125,2.0,587.625000

In [ ]:
def imputing_1(data, input_cols, output_col):
  imputer = datawig.SimpleImputer(
    input_columns=input_cols, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column=output_col, # 컬럼 0의 missing value를 채운다.
    )
  imputer.fit(train_df=data, num_epochs=50)
  df_null_only = data[data[output_col].isnull()]
  np_imputed = imputer.predict(df_null_only)
  df_imputed = pd.DataFrame(np_imputed)
  data[output_col][data[output_col].isnull()] = df_imputed[output_col+'_imputed']

In [ ]:
df.isnull().sum()

SK_ID_CURR                             0
TARGET                                 0
NAME_CONTRACT_TYPE                     0
CODE_GENDER                            0
DAYS_BIRTH                             0
DAYS_REGISTRATION                      0
REGION_RATING_CLIENT_W_CITY            0
HOUR_APPR_PROCESS_START                0
EXT_SOURCE_1                      173377
EXT_SOURCE_2                         660
EXT_SOURCE_3                       60964
new_ANNUITY_INCOME                    12
new_CREDIT_INCOME                      0
new_GOODS_INCOME                     276
new_REGION                             0
new_REQ_CREDIT                         0
new_HOME_TYPE                          0
new_EDU_LEVEL                          0
new_EMPLOYED_DAYS                  55374
new_ECONOMIC_POPULATION                0
previous_AMT_ANNUITY                 417
previous_AMT_CREDIT                    0
previous_AMT_GOODS_PRICE             975
previous_ID_COUNT                      0
previous_APPLICATION_TO_CREDIT         0
previous_REFUSED_COUNT                 0
previous_DAY_DECISION                  0
dtype: int64

In [ ]:
column_name = list(df.columns)
null_column = []
not_null_column = []

for i in column_name:
  if df[i].isnull().sum() == 0:
    not_null_column.append(i)
  else:
    null_column.append(i)

del not_null_column[0]

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='EXT_SOURCE_1', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['EXT_SOURCE_1'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['EXT_SOURCE_1'][df['EXT_SOURCE_1'].isnull()] = df_imputed['EXT_SOURCE_1_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='EXT_SOURCE_2', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['EXT_SOURCE_2'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['EXT_SOURCE_2'][df['EXT_SOURCE_2'].isnull()] = df_imputed['EXT_SOURCE_2_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='EXT_SOURCE_3', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['EXT_SOURCE_3'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['EXT_SOURCE_3'][df['EXT_SOURCE_3'].isnull()] = df_imputed['EXT_SOURCE_3_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='new_ANNUITY_INCOME', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['new_ANNUITY_INCOME'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['new_ANNUITY_INCOME'][df['new_ANNUITY_INCOME'].isnull()] = df_imputed['new_ANNUITY_INCOME_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='new_GOODS_INCOME', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['new_GOODS_INCOME'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['new_GOODS_INCOME'][df['new_GOODS_INCOME'].isnull()] = df_imputed['new_GOODS_INCOME_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='new_EMPLOYED_DAYS', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['new_EMPLOYED_DAYS'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['new_EMPLOYED_DAYS'][df['new_EMPLOYED_DAYS'].isnull()] = df_imputed['new_EMPLOYED_DAYS_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='previous_AMT_ANNUITY', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['previous_AMT_ANNUITY'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['previous_AMT_ANNUITY'][df['previous_AMT_ANNUITY'].isnull()] = df_imputed['new_EMPLOYED_DAYS_imputed']

In [ ]:
imputer = datawig.SimpleImputer(
    input_columns=not_null_column, # impute에 사용할 컬럼을 지정해줄수 있다. 컬럼 '3'은 제외시켰다.
    output_column='previous_AMT_GOODS_PRICE', # 컬럼 0의 missing value를 채운다.
    )
imputer.fit(train_df=df, num_epochs=50)
df_null_only = df[df['previous_AMT_GOODS_PRICE'].isnull()]
np_imputed = imputer.predict(df_null_only)
df_imputed = pd.DataFrame(np_imputed)
df['previous_AMT_GOODS_PRICE'][df['previous_AMT_GOODS_PRICE'].isnull()] = df_imputed['previous_AMT_GOODS_PRICE_imputed']

# 샘플링

In [ ]:
from sklearn.preprocessing import LabelEncoder
from imblearn.combine import SMOTETomek

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/dataset/2022_겨울_학술_dataset/total_imputed.csv',index_col=0)

In [ ]:
df.isnull().sum()

SK_ID_CURR                        0
TARGET                            0
NAME_CONTRACT_TYPE                0
CODE_GENDER                       0
DAYS_BIRTH                        0
DAYS_REGISTRATION                 0
REGION_RATING_CLIENT_W_CITY       0
HOUR_APPR_PROCESS_START           0
EXT_SOURCE_1                      0
new_CREDIT_INCOME                 0
new_REGION                        0
new_REQ_CREDIT                    0
new_HOME_TYPE                     0
new_EDU_LEVEL                     0
new_ECONOMIC_POPULATION           0
previous_AMT_CREDIT               0
previous_ID_COUNT                 0
previous_APPLICATION_TO_CREDIT    0
previous_REFUSED_COUNT            0
previous_DAY_DECISION             0
EXT_SOURCE_2                      0
EXT_SOURCE_3                      0
new_EMPLOYED_DAYS                 0
new_GOODS_INCOME                  0
previous_AMT_GOODS_PRICE          0
new_ANNUITY_INCOME                0
previous_AMT_ANNUITY              0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 307509 entries, 0 to 307508
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   SK_ID_CURR                      307509 non-null  int64
 1   TARGET                          307509 non-null  int64
 2   NAME_CONTRACT_TYPE              307509 non-null  object
 3   CODE_GENDER                     307509 non-null  object
 4   DAYS_BIRTH                      307509 non-null  int64
 5   DAYS_REGISTRATION               307509 non-null  float64
 6   REGION_RATING_CLIENT_W_CITY     307509 non-null  int64
 7   HOUR_APPR_PROCESS_START         307509 non-null  int64
 8   EXT_SOURCE_1                    307509 non-null  float64
 9   new_CREDIT_INCOME               307509 non-null  float64
 10  new_REGION                      307509 non-null  int64
 11  new_REQ_CREDIT                  307509 non-null  int64
 12  new_HOME_TYPE                   307509 non-null  int64
 13  new_EDU_LEVEL                   307509 non-null  int64
 14  new_ECONOMIC_POPULATION         307509 non-null  float64
 15  previous_AMT_CREDIT             307509 non-null  float64
 16  previous_ID_COUNT               307509 non-null  float64
 17  previous_APPLICATION_TO_CREDIT  307509 non-null  float64
 18  previous_REFUSED_COUNT          307509 non-null  float64
 19  previous_DAY_DECISION           307509 non-null  float64
 20  EXT_SOURCE_2                    307509 non-null  float64
 21  EXT_SOURCE_3                    307509 non-null  float64
 22  new_EMPLOYED_DAYS               307509 non-null  float64
 23  new_GOODS_INCOME                307509 non-null  float64
 24  previous_AMT_GOODS_PRICE        307509 non-null  float64
 25  new_ANNUITY_INCOME              307509 non-null  float64
 26  previous_AMT_ANNUITY            307509 non-null  float64
dtypes: float64(16), int64(9), object(2)
memory usage: 65.7+ MB

In [ ]:
le = LabelEncoder()

df['NAME_CONTRACT_TYPE'] = le.fit_transform(df['NAME_CONTRACT_TYPE'])
df['CODE_GENDER'] = le.fit_transform(df['CODE_GENDER'])

In [ ]:
X_imb = df.drop(['TARGET','SK_ID_CURR'],axis=1)
y_imb = df['TARGET']

In [ ]:
smt = SMOTETomek(sampling_strategy='auto', random_state=42)

In [ ]:
X_samp, y_samp = smt.fit_resample(X_imb, y_imb)

In [ ]:
X_samp.to_csv('__1.csv')
y_samp.to_csv('__2.csv')